import React from "react";
import img1 from "./images/car.png";
import img2 from "./images/car1.jpeg";
import img3 from "./images/car3.jpeg";
import img4 from "./images/car4.jpeg";
import img5 from "./images/car5.jpeg";
import img6 from "./images/car6.jpeg";

export const CarsData = {
  cars0: [
    {
      id: 1,
      img: img1,
      Car: "Toyota RAV4",
      year: 2021,
      Fuel: "Hybird",
      Persons: 4,
      Mileage: 6.1,
      Design: "Automatic",
      Rent: 440,
    },
    {
      id: 2,
      img: img2,
      Car: "BMW",
      year: 2019,
      Fuel: "Hybird",
      Persons: 4,
      Mileage: 6.1,
      Design: "Automatic",
      Rent: 440,
    },
    {
      id: 3,
      img: img3,
      Car: "VOLKSWAGEN",
      year: 2021,
      Fuel: "Hybird",
      Persons: 4,
      Mileage: 6.1,
      Design: "Automatic",
      Rent: 440,
    },
    {
      id: 4,
      img: img4,
      Car: "AUDI",
      year: 2023,
      Fuel: "Hybird",
      Persons: 4,
      Mileage: 6.1,
      Design: "Automatic",
      Rent: 440,
    },
    {
      id: 5,
      img: img5,
      Car: "HONDA",
      year: 2003,
      Fuel: "Hybird",
      Persons: 4,
      Mileage: 6.1,
      Design: "Automatic",
      Rent: 440,
    },
    {
      id: 6,
      img: img6,
      Car: "BENZ",
      year: 2029,
      Fuel: "Hybird",
      Persons: 4,
      Mileage: 6.1,
      Design: "Automatic",
      Rent: 440,
    },
  ],

  cars1: [
    {
      id: 1,
      img: img6,
      Car: "Toyota RAV4",
      year: 2021,
      Fuel: "Hybird",
      Persons: 4,
      Mileage: 6.1,
      Design: "Automatic",
      Rent: 440,
    },
    {
      id: 2,
      img: img5,
      Car: "BMW",
      year: 2019,
      Fuel: "Hybird",
      Persons: 4,
      Mileage: 6.1,
      Design: "Automatic",
      Rent: 440,
    },
    {
      id: 3,
      img: img4,
      Car: "VOLKSWAGEN",
      year: 2021,
      Fuel: "Hybird",
      Persons: 4,
      Mileage: 6.1,
      Design: "Automatic",
      Rent: 440,
    },
    {
      id: 4,
      img: img3,
      Car: "AUDI",
      year: 2023,
      Fuel: "Hybird",
      Persons: 4,
      Mileage: 6.1,
      Design: "Automatic",
      Rent: 440,
    },
    {
      id: 5,
      img: img2,
      Car: "HONDA",
      year: 2003,
      Fuel: "Hybird",
      Persons: 4,
      Mileage: 6.1,
      Design: "Automatic",
      Rent: 440,
    },
    {
      id: 6,
      img: img1,
      Car: "BENZ",
      year: 2029,
      Fuel: "Hybird",
      Persons: 4,
      Mileage: 6.1,
      Design: "Automatic",
      Rent: 440,
    },
  ],
};
